"""Add composes.date_respin column


Revision ID: 0720c0281233
Revises: 18c15f736b50
Create Date: 2022-11-23 13:18:06.165983

"""

# revision identifiers, used by Alembic.
revision = "0720c0281233"
down_revision = "18c15f736b50"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("composes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_respin", sa.String(), nullable=True))
        batch_op.create_unique_constraint("uq_composes_date_respin", ["date_respin"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("composes", schema=None) as batch_op:
        batch_op.drop_constraint("uq_composes_date_respin", type_="unique")
        batch_op.drop_column("date_respin")

    # ### end Alembic commands ###
