"""Add composes.compose_url

Revision ID: 18c15f736b50
Revises: 16cd8140b6c7
Create Date: 2021-01-28 03:37:51.165757

"""

# revision identifiers, used by Alembic.
revision = "18c15f736b50"
down_revision = "16cd8140b6c7"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("composes", sa.Column("compose_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("composes", "compose_url")
    # ### end Alembic commands ###
