"""Add tagger_groups and untagger_groups

Revision ID: f6020a9602bb
Revises: 8d24c19f61ef
Create Date: 2024-08-20 11:54:03.302376

"""

# revision identifiers, used by Alembic.
revision = "f6020a9602bb"
down_revision = "8d24c19f61ef"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tagger_groups",
        sa.Column("group", sa.String(length=200), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("group", "tag_id", name="tagger_groups_pk"),
    )
    op.create_table(
        "untagger_groups",
        sa.Column("group", sa.String(length=200), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("group", "tag_id", name="untagger_groups_pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("untagger_groups")
    op.drop_table("tagger_groups")
    # ### end Alembic commands ###
