FROM quay.io/exd-guild-compose/cts:latest

LABEL \
    name="CTS test" \
    description="Run tests using tox" \
    vendor="CTS developers" \
    license="MIT"

RUN dnf -y install \
    findutils \
    make \
    python3-ldap \
    python3-mock \
    python3-sphinx \
    python3-tox \
    && dnf clean all

WORKDIR /src

CMD ["tox"]
