FROM registry.fedoraproject.org/fedora-minimal:45

RUN microdnf install -y python3 python3-pip && \
    microdnf clean all && \
    pip3 install --no-cache-dir ldaptor twisted

COPY server.py /app/server.py

EXPOSE 1389

USER 1001

CMD ["python3", "/app/server.py"]
