name: Gating

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest
    container:
      image: quay.io/exd-guild-compose/cts:latest

    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: >
          sudo dnf update -y &&
          sudo dnf install -y
          findutils
          make
          python3-ldap
          python3-mock
          python3-sphinx
          python3-tox
      - name: bandit
        run: tox -e bandit
      - name: black
        run: tox -e black
      - name: flake8
        run: tox -e flake8
      - name: docs
        run: tox -e docs
      - name: tests
        run: tox -e py3
